# Generated by Django 5.2.6 on 2025-10-22 16:20

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Arbitros",
            fields=[
                (
                    "idArb",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID:"
                    ),
                ),
                (
                    "nomArb",
                    models.CharField(max_length=50, verbose_name="Nom. completo:"),
                ),
                (
                    "telArb",
                    models.CharField(
                        max_length=9,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="El teléfono de contacto sólo debe contener números.",
                                regex="^\\d+$",
                            )
                        ],
                        verbose_name="Teléfono de contacto:",
                    ),
                ),
                (
                    "conArb",
                    models.EmailField(
                        max_length=75, verbose_name="Correo de contacto:"
                    ),
                ),
            ],
            options={
                "verbose_name": "Árbitro",
                "verbose_name_plural": "Árbitros",
                "db_table": "ARBITROS",
            },
        ),
        migrations.CreateModel(
            name="Disciplinas",
            fields=[
                (
                    "idDis",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID:"
                    ),
                ),
                (
                    "nomDis",
                    models.CharField(
                        max_length=50, verbose_name="Nom. de la disciplina:"
                    ),
                ),
                (
                    "min_equipos",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Mín. de equipos por encuentro:"
                    ),
                ),
                (
                    "max_equipos",
                    models.PositiveIntegerField(
                        default=10, verbose_name="Máx. de equipos por encuentro:"
                    ),
                ),
                (
                    "min_participantes_por_equipo",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Mín. de participantes por equipo:"
                    ),
                ),
                (
                    "max_participantes_por_equipo",
                    models.PositiveIntegerField(
                        default=10, verbose_name="Máx. de participantes por equipo:"
                    ),
                ),
                (
                    "duracion_estimada",
                    models.DurationField(
                        default=datetime.timedelta(seconds=3600),
                        verbose_name="Duración estimada del encuentro:",
                    ),
                ),
            ],
            options={
                "verbose_name": "Disciplina",
                "verbose_name_plural": "Disciplinas",
                "db_table": "DISCIPLINAS",
            },
        ),
        migrations.CreateModel(
            name="Encuentros",
            fields=[
                (
                    "idEnc",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID:"
                    ),
                ),
                ("finiEnc", models.DateTimeField(verbose_name="Fecha de inicio:")),
                (
                    "ffinEnc",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de fin:"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("CONFIRMADO", "Confirmado"),
                            ("EN_PROGRESO", "En Progreso"),
                            ("FINALIZADO", "Finalizado"),
                        ],
                        default="CONFIRMADO",
                        max_length=15,
                        verbose_name="Estado del encuentro:",
                    ),
                ),
                (
                    "arbitro",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="register_par.arbitros",
                        verbose_name="Árbitro asociado:",
                    ),
                ),
                (
                    "idDis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="register_par.disciplinas",
                        verbose_name="Disciplina:",
                    ),
                ),
            ],
            options={
                "verbose_name": "Encuentro",
                "verbose_name_plural": "Encuentros",
                "db_table": "ENCUENTROS",
            },
        ),
        migrations.CreateModel(
            name="EncuentroEquipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "encuentro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="register_par.encuentros",
                    ),
                ),
            ],
            options={
                "verbose_name": "Equipo participante",
                "verbose_name_plural": "Equipos participantes",
                "db_table": "ENCUENTRO_EQUIPO",
            },
        ),
        migrations.CreateModel(
            name="Equipos",
            fields=[
                (
                    "idEqu",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID:"
                    ),
                ),
                (
                    "nomEqu",
                    models.CharField(max_length=25, verbose_name="Nom. del equipo:"),
                ),
                (
                    "oliEqu",
                    models.CharField(
                        choices=[("S", "Sí"), ("N", "No")],
                        max_length=1,
                        verbose_name="¿Es olímpico?",
                    ),
                ),
            ],
            options={
                "verbose_name": "Equipo",
                "verbose_name_plural": "Equipos",
                "db_table": "EQUIPOS",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("oliEqu__in", ["S", "N"])),
                        name="check_oliEqu",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="encuentros",
            name="equipos",
            field=models.ManyToManyField(
                through="register_par.EncuentroEquipo",
                to="register_par.equipos",
                verbose_name="Equipos participantes:",
            ),
        ),
        migrations.AddField(
            model_name="encuentroequipo",
            name="equipo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="register_par.equipos"
            ),
        ),
        migrations.CreateModel(
            name="Participantes",
            fields=[
                (
                    "idPar",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID:"
                    ),
                ),
                (
                    "nomPar",
                    models.CharField(max_length=75, verbose_name="Nom. completo:"),
                ),
                ("fecPar", models.DateField(verbose_name="Fecha de nacimiento:")),
                ("curPar", models.CharField(max_length=5, verbose_name="Curso:")),
                (
                    "telPar",
                    models.CharField(
                        max_length=9,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="El teléfono de contacto sólo debe contener números.",
                                regex="^\\d+$",
                            )
                        ],
                        verbose_name="Teléfono de contacto:",
                    ),
                ),
                (
                    "conPar",
                    models.EmailField(
                        max_length=75, verbose_name="Correo de contacto:"
                    ),
                ),
                (
                    "equipo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="participantes",
                        to="register_par.equipos",
                        verbose_name="Equipo asociado:",
                    ),
                ),
            ],
            options={
                "verbose_name": "Participante",
                "verbose_name_plural": "Participantes",
                "db_table": "PARTICIPANTES",
            },
        ),
        migrations.CreateModel(
            name="Pistas",
            fields=[
                (
                    "idPis",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID:"
                    ),
                ),
                (
                    "nomPis",
                    models.CharField(max_length=25, verbose_name="Nom. de la pista:"),
                ),
                (
                    "cubPis",
                    models.CharField(
                        choices=[("S", "Sí"), ("N", "No")],
                        max_length=1,
                        verbose_name="¿Está cubierta?",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pista",
                "verbose_name_plural": "Pistas",
                "db_table": "PISTAS",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("cubPis__in", ["S", "N"])),
                        name="check_cubPis",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="encuentros",
            name="idPis",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="register_par.pistas",
                verbose_name="Pista:",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="encuentroequipo",
            unique_together={("encuentro", "equipo")},
        ),
        migrations.AddConstraint(
            model_name="encuentros",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("ffinEnc__gt", models.F("finiEnc")),
                    ("ffinEnc__isnull", True),
                    _connector="OR",
                ),
                name="check_fechas_encuentro",
            ),
        ),
    ]
