# Generated by Django 5.2.6 on 2025-09-25 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_par', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbitros',
            name='conArb',
            field=models.EmailField(max_length=75, verbose_name='Correo de contacto:'),
        ),
        migrations.AlterField(
            model_name='arbitros',
            name='nomArb',
            field=models.CharField(max_length=50, verbose_name='Nombre completo:'),
        ),
        migrations.AlterField(
            model_name='arbitros',
            name='telArb',
            field=models.CharField(max_length=9, verbose_name='Teléfono de contacto:'),
        ),
        migrations.AlterField(
            model_name='disciplinas',
            name='nomDis',
            field=models.CharField(max_length=50, verbose_name='Nombre de la disciplina:'),
        ),
        migrations.AlterField(
            model_name='encuentroequipo',
            name='rol',
            field=models.CharField(choices=[('L', 'Local'), ('V', 'Visitante')], max_length=1, verbose_name='Rol del equipo:'),
        ),
        migrations.AlterField(
            model_name='encuentros',
            name='arbitro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='register_par.arbitros', verbose_name='Árbitro asociado:'),
        ),
        migrations.AlterField(
            model_name='encuentros',
            name='equipos',
            field=models.ManyToManyField(through='register_par.EncuentroEquipo', to='register_par.equipos', verbose_name='Equipos participantes:'),
        ),
        migrations.AlterField(
            model_name='encuentros',
            name='ffinEnc',
            field=models.DateTimeField(verbose_name='Fecha de fin:'),
        ),
        migrations.AlterField(
            model_name='encuentros',
            name='finiEnc',
            field=models.DateTimeField(verbose_name='Fecha de inicio:'),
        ),
        migrations.AlterField(
            model_name='encuentros',
            name='idDis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register_par.disciplinas', verbose_name='Disciplina:'),
        ),
        migrations.AlterField(
            model_name='encuentros',
            name='idPis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register_par.pistas', verbose_name='Pista:'),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='nomEqu',
            field=models.CharField(max_length=25, verbose_name='Nombre del equipo:'),
        ),
        migrations.AlterField(
            model_name='participantes',
            name='conPar',
            field=models.EmailField(max_length=75, verbose_name='Correo de contacto:'),
        ),
        migrations.AlterField(
            model_name='participantes',
            name='curPar',
            field=models.CharField(max_length=5, verbose_name='Curso:'),
        ),
        migrations.AlterField(
            model_name='participantes',
            name='fecPar',
            field=models.DateField(verbose_name='Fecha de nacimiento:'),
        ),
        migrations.AlterField(
            model_name='participantes',
            name='nomPar',
            field=models.CharField(max_length=75, verbose_name='Nombre completo:'),
        ),
        migrations.AlterField(
            model_name='participantes',
            name='telPar',
            field=models.CharField(max_length=9, verbose_name='Teléfono de contacto:'),
        ),
        migrations.AlterField(
            model_name='pistas',
            name='nomPis',
            field=models.CharField(max_length=25, verbose_name='Nombre de la pista:'),
        ),
    ]
