# Generated by Django 5.2.6 on 2025-09-30 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_par', '0002_alter_arbitros_conarb_alter_arbitros_nomarb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplinas',
            name='max_equipos',
            field=models.PositiveIntegerField(default=2, verbose_name='Máximo de equipos por encuentro:'),
        ),
        migrations.AddField(
            model_name='disciplinas',
            name='max_participantes_por_equipo',
            field=models.PositiveIntegerField(default=10, verbose_name='Máximo de participantes por equipo:'),
        ),
        migrations.AddField(
            model_name='disciplinas',
            name='min_equipos',
            field=models.PositiveIntegerField(default=2, verbose_name='Mínimo de equipos por encuentro:'),
        ),
        migrations.AddField(
            model_name='disciplinas',
            name='min_participantes_por_equipo',
            field=models.PositiveIntegerField(default=1, verbose_name='Mínimo de participantes por equipo:'),
        ),
    ]
