# Generated by Django 5.2.6 on 2025-10-08 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_par', '0003_disciplinas_max_equipos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplinas',
            name='max_equipos',
            field=models.PositiveIntegerField(default=10, verbose_name='Máximo de equipos por encuentro:'),
        ),
        migrations.AlterField(
            model_name='disciplinas',
            name='min_equipos',
            field=models.PositiveIntegerField(default=1, verbose_name='Mínimo de equipos por encuentro:'),
        ),
    ]
